This notebook (and the slides from lecture 8) will help you go straight from training a model in Colab to deploying it in a webpage with TensorFlow.js - without having to leave the browser.

Configure this notebook to work with your GitHub account by populating these fields.

In [1]:
import numpy as np

In [2]:
# !pip install tensorflowjs

In [3]:
# your github username
USER_NAME = "pinhao1994"

# the email associated with your commits
# (may not matter if you leave it as this)
USER_EMAIL = "pinhao1994@gmail.com"

# the user token you've created (see the lecture 8 slides for instructions)
TOKEN = open("acctoken.txt", "r").read() 

# site name
# for example, if my user_name is "foo", then this notebook will create
# a site at https://foo.github.io/hw4/
SITE_NAME = "ADL/a4"

Next, run this cell to configure git.

In [4]:
!git config --global user.email {USER_NAME}
!git config --global user.name  {USER_EMAIL}

Clone your GitHub pages repo (see the lecture 8 slides for instructions on how to create one).

In [5]:
import os
repo_path = USER_NAME + '.github.io'
if not os.path.exists(os.path.join(os.getcwd(), repo_path)):
  !git clone https://{USER_NAME}:{TOKEN}@github.com/{USER_NAME}/{USER_NAME}.github.io

In [6]:
os.chdir(repo_path)
!git pull

Already up to date.


Create a folder for your site.

In [7]:
project_path = os.path.join(os.getcwd(), SITE_NAME)
if not os.path.exists(project_path): 
  os.mkdir(project_path)
os.chdir(project_path)

These paths will be used by the converter script.

In [8]:
# DO NOT MODIFY
MODEL_DIR = os.path.join(project_path, "model_js")
if not os.path.exists(MODEL_DIR):
  os.mkdir(MODEL_DIR)

As an example, we will create and vectorize a few documents. (Check out https://www.gutenberg.org/ for a bunch of free e-books.)

In [9]:
import requests
import re

In [10]:
def read_text_from(url, read_lines=1000):
    req = requests.get(url)
    content = re.sub(r"[^a-zA-Z0-9 .]+", '', req.text)
    text = re.sub(r"[ ]+", " ", content.lower())
    return re.match(r'(?:[^.:;]+[.:;]){%d}' % read_lines, text).group().split(". ")

In [11]:
book1 = read_text_from(url="http://www.gutenberg.org/cache/epub/28885/pg28885.txt")
book2 = read_text_from(url="http://www.gutenberg.org/cache/epub/345/pg345.txt", read_lines=318)  # avoid re problem
book3 = read_text_from(url="http://www.gutenberg.org/cache/epub/6130/pg6130.txt")

In [12]:
x_train = [*book1, *book2, *book3]
y_train = [*[0]*len(book1), *[1]*len(book2), *[2]*len(book3)]

In [13]:
# # A few snippets from Alice in Wonderland
# ex1 = "Alice was beginning to get very tired of sitting by her sister on the bank."
# ex2 = "Once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it."

# # Dracula
# ex3 = "Buda-Pesth seems a wonderful place."
# ex4 = "Left Munich at 8:35 P. M., on 1st May, arriving at Vienna early next morning."

# # Illiad
# ex5 = "Scepticism was as much the result of knowledge, as knowledge is of scepticism."
# ex6 = "To be content with what we at present know, is, for the most part, to shut our ears against conviction."

# # A Surgeon in Arms
# ex7 = 'Life "out there" is so strange, so unique, so full of hardship and danger, and' \
#     'yet so intensely interesting that it seems like another world.'  
# ex8 = 'It is a different life from any other that is to be found in our world today.'

In [14]:
# x_train = [ex1, ex2, ex3, ex4, ex5, ex6, ex7, ex8]
# y_train = [0, 0, 1, 1, 2, 2, 3, 3] # Indicating which book each sentence is from

Tokenize the documents, create a word index (word -> number).

In [15]:
max_len = 20
num_words = 1000

from keras.preprocessing.text import Tokenizer
# Fit the tokenizer on the training data
t = Tokenizer(num_words=num_words)
t.fit_on_texts(x_train)

Using TensorFlow backend.


In [16]:
print(t.word_index)

{'the': 1, 'and': 2, 'of': 3, 'to': 4, 'a': 5, 'in': 6, 'it': 7, 'i': 8, 'that': 9, 'as': 10, 'was': 11, 'with': 12, 'his': 13, 'said': 14, 'she': 15, 'is': 16, 'he': 17, 'you': 18, 'alice': 19, 'for': 20, 'but': 21, 'on': 22, 'at': 23, 'be': 24, 'not': 25, 'this': 26, 'all': 27, 'they': 28, 'which': 29, 'had': 30, 'so': 31, 'by': 32, 'her': 33, 'what': 34, 'from': 35, 'or': 36, 'have': 37, 'we': 38, 'are': 39, 'my': 40, 'one': 41, 'if': 42, 'no': 43, 'were': 44, 'very': 45, 'their': 46, 'its': 47, 'out': 48, 'an': 49, 'them': 50, 'him': 51, 'like': 52, 'then': 53, 'when': 54, 'more': 55, 'who': 56, 'me': 57, 'there': 58, 'up': 59, 'some': 60, 'little': 61, 'would': 62, 'down': 63, 'could': 64, 'into': 65, 'now': 66, 'know': 67, 'great': 68, 'our': 69, 'been': 70, 'homer': 71, 'has': 72, 'time': 73, 'may': 74, 'such': 75, 'than': 76, 'must': 77, 'first': 78, 'will': 79, 'do': 80, 'only': 81, 'see': 82, 'about': 83, 'much': 84, 'thy': 85, 'went': 86, 'king': 87, 'shall': 88, 'again': 89

Here's how we vectorize a document.

In [17]:
# vectorized = t.texts_to_sequences([ex1])
vectorized = t.texts_to_sequences([x_train[0]])
print(vectorized)

[[690, 388, 866, 6, 32, 448, 16, 20, 1, 212, 3, 988, 23, 43, 2, 43]]


Apply padding if necessary.

In [18]:
from keras.preprocessing.sequence import pad_sequences
padded = pad_sequences(vectorized, maxlen=max_len, padding='post')

In [19]:
print(padded)

[[690 388 866   6  32 448  16  20   1 212   3 988  23  43   2  43   0   0
    0   0]]


We will save the word index in metadata. Later, we'll use it to convert words typed in the browser to numbers for prediction.

In [20]:
metadata = {
  'word_index': t.word_index,
  'max_len': max_len,
  'vocabulary_size': num_words,
}

Define a model.

In [21]:
embedding_size = 8
n_classes = np.unique(y_train).shape[0]
epochs = 10

import keras
model = keras.Sequential()
model.add(keras.layers.Embedding(num_words, embedding_size, input_shape=(max_len,)))
model.add(keras.layers.LSTM(32, activation="relu", return_sequences=True))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(n_classes, activation='softmax'))
model.compile('adam', 'sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 8)             8000      
_________________________________________________________________
lstm_1 (LSTM)                (None, 20, 32)            5248      
_________________________________________________________________
flatten_1 (Flatten)          (None, 640)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 1923      
Total params: 15,171
Trainable params: 15,171
Non-trainable params: 0
_________________________________________________________________


Prepare some training data.

In [22]:
x_train = t.texts_to_sequences(x_train)
x_train = pad_sequences(x_train, maxlen=max_len, padding='post')
print(x_train)

[[690 388 866 ...   0   0   0]
 [  7 226   7 ... 866   6  32]
 [388 866   6 ...   5 265   2]
 ...
 [  1 146  10 ...   0   0   0]
 [ 75  11   1 ...   0   0   0]
 [445  38  12 ... 429  91 746]]


In [23]:
model.fit(x_train, y_train, epochs=epochs)

Epoch 1/10
1407/1407 [==============================] - 3s 2ms/step - loss: 1.0451 - acc: 0.5139
Epoch 2/10
1407/1407 [==============================] - 2s 1ms/step - loss: 0.9320 - acc: 0.5238
Epoch 3/10
1407/1407 [==============================] - 1s 829us/step - loss: 0.6428 - acc: 0.7342
Epoch 4/10
1407/1407 [==============================] - 1s 878us/step - loss: 0.4713 - acc: 0.7761
Epoch 5/10
1407/1407 [==============================] - 1s 844us/step - loss: 0.3857 - acc: 0.7996
Epoch 6/10
1407/1407 [==============================] - 1s 659us/step - loss: 0.3285 - acc: 0.8422
Epoch 7/10
1407/1407 [==============================] - 1s 634us/step - loss: 0.2863 - acc: 0.8735
Epoch 8/10
1407/1407 [==============================] - 1s 625us/step - loss: 0.2365 - acc: 0.8962
Epoch 9/10
1407/1407 [==============================] - 1s 636us/step - loss: 0.2217 - acc: 0.9069
Epoch 10/10
1407/1407 [==============================] - 1s 616us/step - loss: 0.1865 - acc: 0.9147


Demo using the model to make predictions.

In [24]:
test_example = "Left Munich at 8:35 P. M., on 1st May, arriving at Vienna early next morning."
x_test = t.texts_to_sequences([test_example])
x_test = pad_sequences(x_test, maxlen=max_len, padding='post')
print(x_test)

[[227  23  22  74  23 478 170 639   0   0   0   0   0   0   0   0   0   0
    0   0]]


In [25]:
preds = model.predict(x_test)
print(preds)
print(np.argmax(preds))

[[0.190427   0.7797792  0.02979377]]
1


Convert the model

In [26]:
import json
import tensorflowjs as tfjs

metadata_json_path = os.path.join(MODEL_DIR, 'metadata.json')
json.dump(metadata, open(metadata_json_path, 'wt'))
tfjs.converters.save_keras_model(model, MODEL_DIR)
print('\nSaved model artifcats in directory: %s' % MODEL_DIR)


Saved model artifcats in directory: /Users/apple/Dropbox/Billy/ADL/HW4/pinhao1994.github.io/ADL/a4/model_js


Write an index.html and an index.js file configured to load our model.

In [27]:
index_html = """
<!doctype html>

<body>
  <style>
    #textfield {
      font-size: 120%;
      width: 60%;
      height: 200px;
    }
  </style>
  <h1>
    Pin-Hao Chen ADL HW4 Part1 DEMO
  </h1>
  <hr>
  <div class="create-model">
    <button id="load-model" style="display:none">Load model</button>
  </div>
  <div>
    <div>
      <span>Vocabulary size: </span>
      <span id="vocabularySize"></span>
    </div>
    <div>
      <span>Max length: </span>
      <span id="maxLen"></span>
    </div>
  </div>
  <hr>
  <div>
    <select id="example-select" class="form-control">
      <option value="example1">Alice's Adventures in Wonderland</option>
      <option value="example2">Dracula</option>
      <option value="example3">The Iliad</option>
      <!--<option value="example4">A Surgeon in Arms</option>-->
    </select>
  </div>
  <div>
    <textarea id="text-entry"></textarea>
  </div>
  <hr>
  <div>
    <span id="status">Standing by.</span>
  </div>

  <script src='https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js'></script>
  <script src='index.js'></script>
</body>
"""

In [28]:
index_js = """
const HOSTED_URLS = {
  model:
      'model_js/model.json',
  metadata:
      'model_js/metadata.json'
};

const examples = {
  'example1':
      'Alice was beginning to get very tired of sitting by her sister on the bank.',
  'example2':
      'Buda-Pesth seems a wonderful place.',
  'example3':
      'Scepticism was as much the result of knowledge, as knowledge is of scepticism.', 
  /*'example4':
      "Life \\"out there\\" is so strange, so unique, so full of hardship and danger, and yet so intensely interesting that it seems like another world."
  */
};

function status(statusText) {
  console.log(statusText);
  document.getElementById('status').textContent = statusText;
}

function showMetadata(metadataJSON) {
  document.getElementById('vocabularySize').textContent =
      metadataJSON['vocabulary_size'];
  document.getElementById('maxLen').textContent =
      metadataJSON['max_len'];
}

function settextField(text, predict) {
  const textField = document.getElementById('text-entry');
  textField.value = text;
  doPredict(predict);
}

function setPredictFunction(predict) {
  const textField = document.getElementById('text-entry');
  textField.addEventListener('input', () => doPredict(predict));
}

function disableLoadModelButtons() {
  document.getElementById('load-model').style.display = 'none';
}

function doPredict(predict) {
  const textField = document.getElementById('text-entry');
  const result = predict(textField.value);
  score_string = "Class scores: ";
  for (var x in result.score) {
    score_string += x + " ->  " + result.score[x].toFixed(3) + ", "
  }
  //console.log(score_string);
  status(
      score_string + ' elapsed: ' + result.elapsed.toFixed(3) + ' ms)');
}

function prepUI(predict) {
  setPredictFunction(predict);
  const testExampleSelect = document.getElementById('example-select');
  testExampleSelect.addEventListener('change', () => {
    settextField(examples[testExampleSelect.value], predict);
  });
  settextField(examples['example1'], predict);
}

async function urlExists(url) {
  status('Testing url ' + url);
  try {
    const response = await fetch(url, {method: 'HEAD'});
    return response.ok;
  } catch (err) {
    return false;
  }
}

async function loadHostedPretrainedModel(url) {
  status('Loading pretrained model from ' + url);
  try {
    const model = await tf.loadModel(url);
    status('Done loading pretrained model.');
    disableLoadModelButtons();
    return model;
  } catch (err) {
    console.error(err);
    status('Loading pretrained model failed.');
  }
}

async function loadHostedMetadata(url) {
  status('Loading metadata from ' + url);
  try {
    const metadataJson = await fetch(url);
    const metadata = await metadataJson.json();
    status('Done loading metadata.');
    return metadata;
  } catch (err) {
    console.error(err);
    status('Loading metadata failed.');
  }
}

class Classifier {

  async init(urls) {
    this.urls = urls;
    this.model = await loadHostedPretrainedModel(urls.model);
    await this.loadMetadata();
    return this;
  }

  async loadMetadata() {
    const metadata =
        await loadHostedMetadata(this.urls.metadata);
    showMetadata(metadata);
    this.maxLen = metadata['max_len'];
    console.log('maxLen = ' + this.maxLen);
    this.wordIndex = metadata['word_index']
  }

  predict(text) {
    // Convert to lower case and remove all punctuations.
    const inputText =
        text.trim().toLowerCase().replace(/(\.|\,|\!)/g, '').split(' ');
    // Look up word indices.
    const inputBuffer = tf.buffer([1, this.maxLen], 'float32');
    for (let i = 0; i < inputText.length; ++i) {
      const word = inputText[i];
      inputBuffer.set(this.wordIndex[word], 0, i);
      //console.log(word, this.wordIndex[word], inputBuffer);
    }
    const input = inputBuffer.toTensor();
    //console.log(input);

    status('Running inference');
    const beginMs = performance.now();
    const predictOut = this.model.predict(input);
    //console.log(predictOut.dataSync());
    const score = predictOut.dataSync();//[0];
    predictOut.dispose();
    const endMs = performance.now();

    return {score: score, elapsed: (endMs - beginMs)};
  }
};

async function setup() {
  if (await urlExists(HOSTED_URLS.model)) {
    status('Model available: ' + HOSTED_URLS.model);
    const button = document.getElementById('load-model');
    button.addEventListener('click', async () => {
      const predictor = await new Classifier().init(HOSTED_URLS);
      prepUI(x => predictor.predict(x));
    });
    button.style.display = 'inline-block';
  }

  status('Standing by.');
}

setup();
"""

In [29]:
with open('index.html','w') as f:
  f.write(index_html)
  
with open('index.js','w') as f:
  f.write(index_js)

In [30]:
!pwd
!ls

/Users/apple/Dropbox/Billy/ADL/HW4/pinhao1994.github.io/ADL/a4
index.html index.js   model_js   python


Commit and push everything. Note: we're storing large binary files in GitHub, this isn't ideal (if you want to deploy a model down the road, better to host it in a cloud storage bucket).

In [31]:
!git add . 
!git commit -m "rewrite the model w/ LSTM"
!git push https://{USER_NAME}:{TOKEN}@github.com/{USER_NAME}/{USER_NAME}.github.io/ master

[master 62a2636] rewrite the model w/ LSTM
 2 files changed, 1 insertion(+), 1 deletion(-)
 rewrite ADL/a4/model_js/group1-shard1of1 (99%)
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 4 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 55.58 KiB | 7.94 MiB/s, done.
Total 7 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/pinhao1994/pinhao1994.github.io/
   8efe3d6..62a2636  master -> master


All done! Hopefully everything worked. You may need to wait a few moments for the changes to appear in your site. If not working, check the JavaScript console for errors (in Chrome: View -> Developer -> JavaScript Console).

In [32]:
print("Now, visit https://%s.github.io/%s/" % (USER_NAME, SITE_NAME))

Now, visit https://pinhao1994.github.io/ADL/a4/


If you are debugging and Chrome is failing to pick up your changes, though you've verified they're present in your GitHub repo, see the second answer to: https://superuser.com/questions/89809/how-to-force-refresh-without-cache-in-google-chrome