This notebook (and the slides from lecture 8) will help you go straight from training a model in Colab to deploying it in a webpage with TensorFlow.js - without having to leave the browser.

Configure this notebook to work with your GitHub account by populating these fields.

In [3]:
!pip install tensorflowjs

In [1]:
# your github username
USER_NAME = "pinhao1994"

# the email associated with your commits
# (may not matter if you leave it as this)
USER_EMAIL = "pinhao1994@gmail.com"

# the user token you've created (see the lecture 8 slides for instructions)
TOKEN = open("acctoken.txt", "r").read() 

# site name
# for example, if my user_name is "foo", then this notebook will create
# a site at https://foo.github.io/hw4/
SITE_NAME = "ADL/a4"

Next, run this cell to configure git.

In [2]:
!git config --global user.email {USER_NAME}
!git config --global user.name  {USER_EMAIL}

Clone your GitHub pages repo (see the lecture 8 slides for instructions on how to create one).

In [3]:
import os
repo_path = USER_NAME + '.github.io'
if not os.path.exists(os.path.join(os.getcwd(), repo_path)):
  !git clone https://{USER_NAME}:{TOKEN}@github.com/{USER_NAME}/{USER_NAME}.github.io

In [4]:
os.chdir(repo_path)
!git pull

Already up to date.


Create a folder for your site.

In [5]:
project_path = os.path.join(os.getcwd(), SITE_NAME)
if not os.path.exists(project_path): 
  os.mkdir(project_path)
os.chdir(project_path)

These paths will be used by the converter script.

In [6]:
# DO NOT MODIFY
MODEL_DIR = os.path.join(project_path, "model_js")
if not os.path.exists(MODEL_DIR):
  os.mkdir(MODEL_DIR)

As an example, we will create and vectorize a few documents. (Check out https://www.gutenberg.org/ for a bunch of free e-books.)

In [7]:
# A few snippets from Alice in Wonderland
ex1 = "Alice was beginning to get very tired of sitting by her sister on the bank."
ex2 = "Once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it."

# Dracula
ex3 = "Buda-Pesth seems a wonderful place."
ex4 = "Left Munich at 8:35 P. M., on 1st May, arriving at Vienna early next morning."

# Illiad
ex5 = "Scepticism was as much the result of knowledge, as knowledge is of scepticism."
ex6 = "To be content with what we at present know, is, for the most part, to shut our ears against conviction."

# A Surgeon in Arms
ex7 = 'Life "out there" is so strange, so unique, so full of hardship and danger, and' \
    'yet so intensely interesting that it seems like another world.'  
ex8 = 'It is a different life from any other that is to be found in our world today.'

In [8]:
x_train = [ex1, ex2, ex3, ex4, ex5, ex6, ex7, ex8]
y_train = [0, 0, 1, 1, 2, 2, 3, 3] # Indicating which book each sentence is from

Tokenize the documents, create a word index (word -> number).

In [9]:
max_len = 20
num_words = 1000

from keras.preprocessing.text import Tokenizer
# Fit the tokenizer on the training data
t = Tokenizer(num_words=num_words)
t.fit_on_texts(x_train)

Using TensorFlow backend.


In [10]:
print(t.word_index)

{'is': 1, 'to': 2, 'of': 3, 'the': 4, 'it': 5, 'so': 6, 'was': 7, 'at': 8, 'her': 9, 'sister': 10, 'on': 11, 'or': 12, 'had': 13, 'in': 14, 'seems': 15, 'a': 16, 'scepticism': 17, 'as': 18, 'knowledge': 19, 'be': 20, 'our': 21, 'life': 22, 'that': 23, 'world': 24, 'alice': 25, 'beginning': 26, 'get': 27, 'very': 28, 'tired': 29, 'sitting': 30, 'by': 31, 'bank': 32, 'once': 33, 'twice': 34, 'she': 35, 'peeped': 36, 'into': 37, 'book': 38, 'reading': 39, 'but': 40, 'no': 41, 'pictures': 42, 'conversations': 43, 'buda': 44, 'pesth': 45, 'wonderful': 46, 'place': 47, 'left': 48, 'munich': 49, '8': 50, '35': 51, 'p': 52, 'm': 53, '1st': 54, 'may': 55, 'arriving': 56, 'vienna': 57, 'early': 58, 'next': 59, 'morning': 60, 'much': 61, 'result': 62, 'content': 63, 'with': 64, 'what': 65, 'we': 66, 'present': 67, 'know': 68, 'for': 69, 'most': 70, 'part': 71, 'shut': 72, 'ears': 73, 'against': 74, 'conviction': 75, 'out': 76, 'there': 77, 'strange': 78, 'unique': 79, 'full': 80, 'hardship': 81, 

Here's how we vectorize a document.

In [11]:
vectorized = t.texts_to_sequences([ex1])
print(vectorized)

[[25, 7, 26, 2, 27, 28, 29, 3, 30, 31, 9, 10, 11, 4, 32]]


Apply padding if necessary.

In [12]:
from keras.preprocessing.sequence import pad_sequences
padded = pad_sequences(vectorized, maxlen=max_len, padding='post')

In [13]:
print(padded)

[[25  7 26  2 27 28 29  3 30 31  9 10 11  4 32  0  0  0  0  0]]


We will save the word index in metadata. Later, we'll use it to convert words typed in the browser to numbers for prediction.

In [14]:
metadata = {
  'word_index': t.word_index,
  'max_len': max_len,
  'vocabulary_size': num_words,
}

Define a model.

In [15]:
embedding_size = 8
n_classes = 4
epochs = 10

import keras
model = keras.Sequential()
model.add(keras.layers.Embedding(num_words, embedding_size, input_shape=(max_len,)))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(n_classes, activation='softmax'))
model.compile('adam', 'sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 8)             8000      
_________________________________________________________________
flatten_1 (Flatten)          (None, 160)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 644       
Total params: 8,644
Trainable params: 8,644
Non-trainable params: 0
_________________________________________________________________


Prepare some training data.

In [16]:
x_train = t.texts_to_sequences(x_train)
x_train = pad_sequences(x_train, maxlen=max_len, padding='post')
print(x_train)

[[25  7 26  2 27 28 29  3 30 31  9 10 11  4 32  0  0  0  0  0]
 [34 35 13 36 37  4 38  9 10  7 39 40  5 13 41 42 12 43 14  5]
 [44 45 15 16 46 47  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [48 49  8 50 51 52 53 11 54 55 56  8 57 58 59 60  0  0  0  0]
 [17  7 18 61  4 62  3 19 18 19  1  3 17  0  0  0  0  0  0  0]
 [ 2 20 63 64 65 66  8 67 68  1 69  4 70 71  2 72 21 73 74 75]
 [ 6 78  6 79  6 80  3 81 82 83 84  6 85 86 23  5 15 87 88 24]
 [ 5  1 16 89 22 90 91 92 23  1  2 20 93 14 21 24 94  0  0  0]]


In [17]:
model.fit(x_train, y_train, epochs=epochs)

Epoch 1/10
8/8 [==============================] - 0s 21ms/step - loss: 1.3906 - acc: 0.2500
Epoch 2/10
8/8 [==============================] - 0s 213us/step - loss: 1.3826 - acc: 0.3750
Epoch 3/10
8/8 [==============================] - 0s 221us/step - loss: 1.3720 - acc: 0.6250
Epoch 4/10
8/8 [==============================] - 0s 318us/step - loss: 1.3613 - acc: 0.7500
Epoch 5/10
8/8 [==============================] - 0s 268us/step - loss: 1.3508 - acc: 0.7500
Epoch 6/10
8/8 [==============================] - 0s 260us/step - loss: 1.3402 - acc: 0.7500
Epoch 7/10
8/8 [==============================] - 0s 222us/step - loss: 1.3297 - acc: 0.7500
Epoch 8/10
8/8 [==============================] - 0s 278us/step - loss: 1.3191 - acc: 1.0000
Epoch 9/10
8/8 [==============================] - 0s 217us/step - loss: 1.3086 - acc: 1.0000
Epoch 10/10
8/8 [==============================] - 0s 265us/step - loss: 1.2980 - acc: 1.0000


Demo using the model to make predictions.

In [18]:
test_example = "Left Munich at 8:35 P. M., on 1st May, arriving at Vienna early next morning."
x_test = t.texts_to_sequences([test_example])
x_test = pad_sequences(x_test, maxlen=max_len, padding='post')
print(x_test)

[[48 49  8 50 51 52 53 11 54 55 56  8 57 58 59 60  0  0  0  0]]


In [19]:
preds = model.predict(x_test)
print(preds)
import numpy as np
print(np.argmax(preds))

[[0.25315917 0.26761693 0.2397365  0.2394874 ]]
1


Convert the model

In [20]:
import json
import tensorflowjs as tfjs

metadata_json_path = os.path.join(MODEL_DIR, 'metadata.json')
json.dump(metadata, open(metadata_json_path, 'wt'))
tfjs.converters.save_keras_model(model, MODEL_DIR)
print('\nSaved model artifcats in directory: %s' % MODEL_DIR)


Saved model artifcats in directory: /Users/apple/Dropbox/Billy/ADL/HW4/pinhao1994.github.io/ADL/a4/model_js


Write an index.html and an index.js file configured to load our model.

In [47]:
index_html = """
<!doctype html>

<body>
  <style>
    #textfield {
      font-size: 120%;
      width: 60%;
      height: 200px;
    }
  </style>
  <h1>
    Pin-Hao Chen ADL HW4 Part1 DEMO
  </h1>
  <hr>
  <div class="create-model">
    <button id="load-model" style="display:none">Load model</button>
  </div>
  <div>
    <div>
      <span>Vocabulary size: </span>
      <span id="vocabularySize"></span>
    </div>
    <div>
      <span>Max length: </span>
      <span id="maxLen"></span>
    </div>
  </div>
  <hr>
  <div>
    <select id="example-select" class="form-control">
      <option value="example1">Alice's Adventures in Wonderland</option>
      <option value="example2">Dracula</option>
      <option value="example3">The Iliad</option>
      <option value="example4">A Surgeon in Arms</option>
    </select>
  </div>
  <div>
    <textarea id="text-entry"></textarea>
  </div>
  <hr>
  <div>
    <span id="status">Standing by.</span>
  </div>

  <script src='https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js'></script>
  <script src='index.js'></script>
</body>
"""

In [58]:
index_js = """
const HOSTED_URLS = {
  model:
      'model_js/model.json',
  metadata:
      'model_js/metadata.json'
};

const examples = {
  'example1':
      'Alice was beginning to get very tired of sitting by her sister on the bank.',
  'example2':
      'Buda-Pesth seems a wonderful place.',
  'example3':
      'Scepticism was as much the result of knowledge, as knowledge is of scepticism.', 
  'example4':
      "Life \\"out there\\" is so strange, so unique, so full of hardship and danger, and yet so intensely interesting that it seems like another world."
};

function status(statusText) {
  console.log(statusText);
  document.getElementById('status').textContent = statusText;
}

function showMetadata(metadataJSON) {
  document.getElementById('vocabularySize').textContent =
      metadataJSON['vocabulary_size'];
  document.getElementById('maxLen').textContent =
      metadataJSON['max_len'];
}

function settextField(text, predict) {
  const textField = document.getElementById('text-entry');
  textField.value = text;
  doPredict(predict);
}

function setPredictFunction(predict) {
  const textField = document.getElementById('text-entry');
  textField.addEventListener('input', () => doPredict(predict));
}

function disableLoadModelButtons() {
  document.getElementById('load-model').style.display = 'none';
}

function doPredict(predict) {
  const textField = document.getElementById('text-entry');
  const result = predict(textField.value);
  score_string = "Class scores: ";
  for (var x in result.score) {
    score_string += x + " ->  " + result.score[x].toFixed(3) + ", "
  }
  //console.log(score_string);
  status(
      score_string + ' elapsed: ' + result.elapsed.toFixed(3) + ' ms)');
}

function prepUI(predict) {
  setPredictFunction(predict);
  const testExampleSelect = document.getElementById('example-select');
  testExampleSelect.addEventListener('change', () => {
    settextField(examples[testExampleSelect.value], predict);
  });
  settextField(examples['example1'], predict);
}

async function urlExists(url) {
  status('Testing url ' + url);
  try {
    const response = await fetch(url, {method: 'HEAD'});
    return response.ok;
  } catch (err) {
    return false;
  }
}

async function loadHostedPretrainedModel(url) {
  status('Loading pretrained model from ' + url);
  try {
    const model = await tf.loadModel(url);
    status('Done loading pretrained model.');
    disableLoadModelButtons();
    return model;
  } catch (err) {
    console.error(err);
    status('Loading pretrained model failed.');
  }
}

async function loadHostedMetadata(url) {
  status('Loading metadata from ' + url);
  try {
    const metadataJson = await fetch(url);
    const metadata = await metadataJson.json();
    status('Done loading metadata.');
    return metadata;
  } catch (err) {
    console.error(err);
    status('Loading metadata failed.');
  }
}

class Classifier {

  async init(urls) {
    this.urls = urls;
    this.model = await loadHostedPretrainedModel(urls.model);
    await this.loadMetadata();
    return this;
  }

  async loadMetadata() {
    const metadata =
        await loadHostedMetadata(this.urls.metadata);
    showMetadata(metadata);
    this.maxLen = metadata['max_len'];
    console.log('maxLen = ' + this.maxLen);
    this.wordIndex = metadata['word_index']
  }

  predict(text) {
    // Convert to lower case and remove all punctuations.
    const inputText =
        text.trim().toLowerCase().replace(/(\.|\,|\!)/g, '').split(' ');
    // Look up word indices.
    const inputBuffer = tf.buffer([1, this.maxLen], 'float32');
    for (let i = 0; i < inputText.length; ++i) {
      const word = inputText[i];
      inputBuffer.set(this.wordIndex[word], 0, i);
      //console.log(word, this.wordIndex[word], inputBuffer);
    }
    const input = inputBuffer.toTensor();
    //console.log(input);

    status('Running inference');
    const beginMs = performance.now();
    const predictOut = this.model.predict(input);
    //console.log(predictOut.dataSync());
    const score = predictOut.dataSync();//[0];
    predictOut.dispose();
    const endMs = performance.now();

    return {score: score, elapsed: (endMs - beginMs)};
  }
};

async function setup() {
  if (await urlExists(HOSTED_URLS.model)) {
    status('Model available: ' + HOSTED_URLS.model);
    const button = document.getElementById('load-model');
    button.addEventListener('click', async () => {
      const predictor = await new Classifier().init(HOSTED_URLS);
      prepUI(x => predictor.predict(x));
    });
    button.style.display = 'inline-block';
  }

  status('Standing by.');
}

setup();
"""

In [59]:
with open('index.html','w') as f:
  f.write(index_html)
  
with open('index.js','w') as f:
  f.write(index_js)

In [60]:
!pwd
!ls

/Users/apple/Dropbox/Billy/ADL/HW4/pinhao1994.github.io/ADL/a4
index.html index.js   model_js


Commit and push everything. Note: we're storing large binary files in GitHub, this isn't ideal (if you want to deploy a model down the road, better to host it in a cloud storage bucket).

In [61]:
!git add . 
!git commit -m "fix example 4 str problem"
!git push https://{USER_NAME}:{TOKEN}@github.com/{USER_NAME}/{USER_NAME}.github.io/ master

[master 361e924] fix example 4 str problem
 1 file changed, 1 insertion(+), 1 deletion(-)
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 4 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 537 bytes | 537.00 KiB/s, done.
Total 5 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/pinhao1994/pinhao1994.github.io/
   59b930d..361e924  master -> master


All done! Hopefully everything worked. You may need to wait a few moments for the changes to appear in your site. If not working, check the JavaScript console for errors (in Chrome: View -> Developer -> JavaScript Console).

In [57]:
print("Now, visit https://%s.github.io/%s/" % (USER_NAME, SITE_NAME))

Now, visit https://pinhao1994.github.io/ADL/a4/


If you are debugging and Chrome is failing to pick up your changes, though you've verified they're present in your GitHub repo, see the second answer to: https://superuser.com/questions/89809/how-to-force-refresh-without-cache-in-google-chrome